site_name: Dyscord

nav:
  - Index: index.md
  - Examples: examples.md
  - Changelog: changelog.md
  - Reference: reference.md
plugins:
  - mkdocstrings:
      default_handler: python
      watch:
        - src/dyscord
      handlers:
          python:
              setup_commands:
                  - import sys
                  - sys.path.append('src')
  - search:
  - autorefs:
theme:
  # name: "readthedocs"
  name: "material"