site_name: Dyscord

nav:
  - Index: index.md
  - Examples: examples.md
  - Changelog: changelog.md
  - Reference: reference.md
plugins:
  - mkdocstrings:
      default_handler: python
      watch:
        - src/dyscord
  - search:
  - autorefs:
theme:
  name: "readthedocs"
  # name: "material"