site_name: Dyscord

nav:
  - Index: index.md
  - Examples:
    - Examples: examples/examples.md
    - Events: examples/events.md
    - Interactions: examples/interactions.md
  - Changelog: changelog.md
  - Reference:
    - references/client.md
    - Objects:
      - references/objects/message.md
      - references/objects/user.md
    - Helpers:
      - references/helpers/questions.md
    - reference.md
plugins:
  - mkdocstrings:
      default_handler: python
      watch:
        - src/dyscord
      handlers:
        python:
          rendering:
            show_source: false
            members_order: source
            show_signature_annotations: false
            show_root_full_path: false
          setup_commands:
            - import sys
            - sys.path.append('src')
          selection:
            inherited_members: true
            filters:
              - "!^_[^_]"
              - "!__class__"
  - search:
  - autorefs:
theme:
  # name: "readthedocs"
  name: "material"