my_test_server = {'d': {
    'afk_channel_id': None,
    'afk_timeout': 300,
    'application_command_count': 0,
    'application_command_counts': {'1': 0, '2': 0, '3': 0},
    'application_id': None,
    'banner': None,
    'channels': [{'id': '804392362629267456',
                  'name': 'Text Channels',
                  'permission_overwrites': [],
                  'position': 0,
                  'type': 4},
                 {'id': '804392362629267457',
                  'name': 'Voice Channels',
                  'nsfw': False,
                  'parent_id': None,
                  'permission_overwrites': [],
                  'position': 2,
                  'type': 4},
                 {'id': '804392362629267458',
                  'last_message_id': '889312406638043146',
                  'name': 'general',
                  'parent_id': '804392362629267456',
                  'permission_overwrites': [],
                  'position': 0,
                  'rate_limit_per_user': 0,
                  'topic': None,
                  'type': 0},
                 {'bitrate': 64000,
                  'id': '804392362629267459',
                  'last_message_id': None,
                  'name': 'General',
                  'parent_id': '804392362629267457',
                  'permission_overwrites': [],
                  'position': 0,
                  'rate_limit_per_user': 0,
                  'rtc_region': None,
                  'type': 2,
                  'user_limit': 0},
                 {'id': '889282264507248650',
                  'last_message_id': None,
                  'name': 'general2',
                  'nsfw': False,
                  'parent_id': '804392362629267456',
                  'permission_overwrites': [],
                  'position': 1,
                  'rate_limit_per_user': 0,
                  'topic': None,
                  'type': 0},
                 {'id': '889282433273438308',
                  'name': 'Cat 2',
                  'nsfw': False,
                  'parent_id': None,
                  'permission_overwrites': [],
                  'position': 1,
                  'type': 4},
                 {'id': '889282465687040031',
                  'last_message_id': None,
                  'name': 'ln',
                  'nsfw': False,
                  'parent_id': '889282433273438308',
                  'permission_overwrites': [],
                  'position': 2,
                  'rate_limit_per_user': 0,
                  'topic': None,
                  'type': 0},
                 {'id': '889282495789547611',
                  'last_message_id': None,
                  'name': 'buttercup',
                  'nsfw': False,
                  'parent_id': '889282433273438308',
                  'permission_overwrites': [],
                  'position': 3,
                  'rate_limit_per_user': 0,
                  'topic': None,
                  'type': 0},
                 {'id': '889282512164110356',
                  'last_message_id': None,
                  'name': 'ln',
                  'nsfw': False,
                  'parent_id': '889282433273438308',
                  'permission_overwrites': [],
                  'position': 4,
                  'rate_limit_per_user': 0,
                  'topic': None,
                  'type': 0}],
    'default_message_notifications': 0,
    'description': None,
    'discovery_splash': None,
    'emojis': [],
    'explicit_content_filter': 0,
    'features': [],
    'guild_hashes': {'channels': {'hash': 'Q4fmYtt64L8', 'omitted': False},
                     'metadata': {'hash': 'BgGdaGJsGTk', 'omitted': False},
                     'roles': {'hash': 'X2r4lEEaYB8', 'omitted': False},
                     'version': 1},
    'guild_scheduled_events': [],
    'icon': None,
    'id': '804392362054910047',
    'joined_at': '2021-09-19T08:42:30.572000+00:00',
    'large': False,
    'lazy': True,
    'max_members': 250000,
    'max_video_channel_users': 25,
    'member_count': 2,
    'members': [{'deaf': False,
                 'hoisted_role': None,
                 'joined_at': '2021-09-19T08:42:30.572000+00:00',
                 'mute': False,
                 'roles': ['889068928008060959'],
                 'user': {'avatar': None,
                          'bot': True,
                          'discriminator': '8248',
                          'id': '889065662641737791',
                          'username': 'test-bot'}}],
    'mfa_level': 0,
    'name': 'Bot Playground',
    'nsfw': False,
    'nsfw_level': 0,
    'owner_id': '185846097284038656',
    'preferred_locale': 'en-US',
    'premium_subscription_count': 0,
    'premium_tier': 0,
    'presences': [],
    'public_updates_channel_id': None,
    'region': 'us-south',
    'roles': [{'color': 0,
               'hoist': False,
               'icon': None,
               'id': '804392362054910047',
               'managed': False,
               'mentionable': False,
               'name': '@everyone',
               'permissions': '1071698660929',
               'position': 0,
               'unicode_emoji': None},
              {'color': 0,
               'hoist': False,
               'icon': None,
               'id': '889068928008060959',
               'managed': True,
               'mentionable': False,
               'name': 'test-bot',
               'permissions': '8',
               'position': 1,
               'tags': {'bot_id': '889065662641737791'},
               'unicode_emoji': None}],
    'rules_channel_id': None,
    'splash': None,
    'stage_instances': [],
    'stickers': [],
    'system_channel_flags': 0,
    'system_channel_id': '804392362629267458',
    'threads': [],
    'unavailable': False,
    'vanity_url_code': None,
    'verification_level': 0,
    'voice_states': []},
    'op': 0,
    's': 2,
    't': 'GUILD_CREATE'}

discord_dev_example = {'id': '2909267986263572999',
                       'name': 'Mason\'s Test Server',
                       'icon': '389030ec9db118cb5b85a732333b7c98',
                       'description': None,
                       'splash': '75610b05a0dd09ec2c3c7df9f6975ea0',
                       'discovery_splash': None,
                       'approximate_member_count': 2,
                       'approximate_presence_count': 2,
                       'features': ['INVITE_SPLASH',
                                    'VANITY_URL',
                                    'COMMERCE',
                                    'BANNER',
                                    'NEWS',
                                    'VERIFIED',
                                    'VIP_REGIONS'],
                       'emojis': [{'name': 'ultrafastparrot',
                                   'roles': [],
                                   'id': '393564762228785161',
                                   'require_colons': True,
                                   'managed': False,
                                   'animated': True,
                                   'available': True}],
                       'banner': '5c3cb8d1bc159937fffe7e641ec96ca7',
                       'owner_id': '53908232506183680',
                       'application_id': None,
                       'region': None,
                       'afk_channel_id': None,
                       'afk_timeout': 300,
                       'system_channel_id': None,
                       'widget_enabled': True,
                       'widget_channel_id': '639513352485470208',
                       'verification_level': 0,
                       'roles': [
                           {'id': '2909267986263572999',
                            'name': '@everyone',
                            'permissions': '49794752',
                            'position': 0,
                            'color': 0,
                            'hoist': False,
                            'managed': False,
                            'mentionable': False}],
                       'default_message_notifications': 1,
                       'mfa_level': 0,
                       'explicit_content_filter': 0,
                       'max_presences': None,
                       'max_members': 250000,
                       'max_video_channel_users': 25,
                       'vanity_url_code': 'no',
                       'premium_tier': 0,
                       'premium_subscription_count': 0,
                       'system_channel_flags': 0,
                       'preferred_locale': 'en-US',
                       'rules_channel_id': None,
                       'public_updates_channel_id': None}

partial_guild_object = {
    'id': '80351110224678912',
    'name': '1337 Krew',
    'icon': '8342729096ea3675442027381ff50dfe',
    'owner': True,
    'permissions': '36953089',
    'features': ['COMMUNITY', 'NEWS']
}
