version: '3.4'

services:
    dyscord-jupyter:
        build:
          context: ../../
          dockerfile: tools/jupyter/Dockerfile
          network: host
        ports:
          - 8888:8888
          - 8000:8000
        user: "${UID}:${GID}"
        volumes:
          - ./examples/:/home/jovyan/examples/
          - ../../src/dyscord:/opt/conda/lib/python3.9/site-packages/dyscord:ro
        command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --ip=${HOST_ADDRESS} --ServerApp.root_dir='/home/jovyan/examples/'"
        network_mode: host
        environment:
          - JUPYTER_ENABLE_LAB=yes
