import json
import pathlib

button_press_interaction = {'application_id': '889065662641737791',
                            'channel_id': '804392362629267458',
                            'data': {'component_type': 2,
                                     'custom_id': 'c1da3900-fcd4-47fd-9795-93b25f8b901e'},
                            'guild_id': '804392362054910047',
                            'id': '892512473717030932',
                            'member': {'avatar': None,
                                       'deaf': False,
                                       'is_pending': False,
                                       'joined_at': '2021-01-28T16:48:04.105000+00:00',
                                       'mute': False,
                                       'nick': None,
                                       'pending': False,
                                       'permissions': '1099511627775',
                                       'premium_since': None,
                                       'roles': [],
                                       'user': {'avatar': 'b437e9bd4b0e487a097c4538c6cdce3f',
                                                'discriminator': '2585',
                                                'id': '185846097284038656',
                                                'public_flags': 0,
                                                'username': 'Soton'}},
                            'message': {'attachments': [],
                                        'author': {'avatar': None,
                                                   'bot': True,
                                                   'discriminator': '8248',
                                                   'id': '889065662641737791',
                                                   'public_flags': 0,
                                                   'username': 'test-bot'},
                                        'channel_id': '804392362629267458',
                                        'components': [{'components': [{'custom_id': 'c1da3900-fcd4-47fd-9795-93b25f8b901e',
                                                                        'hash': '',
                                                                        'label': 'DO NOT PRESS',
                                                                        'style': 4,
                                                                        'type': 2}],
                                                        'type': 1}],
                                        'content': 'Hello World!',
                                        'edited_timestamp': None,
                                        'embeds': [],
                                        'flags': 0,
                                        'id': '892512467484278844',
                                        'mention_everyone': False,
                                        'mention_roles': [],
                                        'mentions': [],
                                        'pinned': False,
                                        'timestamp': '2021-09-28T20:45:54.328000+00:00',
                                        'tts': False,
                                        'type': 0},
                            'token': 'aW50ZXJhY3Rpb246ODkyNTEyNDczNzE3MDMwOTMyOnZLSHBwMVYwb3A1dXJWVUhYV0JuOGpDSkpkcGZ6ejJ1ZXY0TWI1R1Bwa2pzWUJidVFrVGp0cUE3U1ZNV0FndkYza1cweHJHQ0hjNVh3aWZMM2RiWWhvYmhIa'
                            'DZoZUhlQ0NEa1NvZkdpRmtjMHZGdnpRYnJKZnYycURXbjFlNERB',
                            'type': 3,
                            'version': 1}

trigger_chat = {'application_id': '889065662641737791',
                'channel_id': '804392362629267458',
                'data': {'id': '891566885043331112',
                         'name': 'test2',
                         'options': [{'name': 'hit_them',
                                      'type': 6,
                                      'value': '185846097284038656'}],
                         'resolved': {'members': {'185846097284038656': {'avatar': None,
                                                                         'is_pending': False,
                                                                         'joined_at': '2021-01-28T16:48:04.105000+00:00',
                                                                         'nick': None,
                                                                         'pending': False,
                                                                         'permissions': '1099511627775',
                                                                         'premium_since': None,
                                                                         'roles': []}},
                                      'users': {'185846097284038656': {'avatar': 'b437e9bd4b0e487a097c4538c6cdce3f',
                                                                       'discriminator': '2585',
                                                                       'id': '185846097284038656',
                                                                       'public_flags': 0,
                                                                       'username': 'Soton'}}},
                         'type': 1},
                'guild_id': '804392362054910047',
                'id': '892534050718351360',
                'member': {'avatar': None,
                           'deaf': False,
                           'is_pending': False,
                           'joined_at': '2021-01-28T16:48:04.105000+00:00',
                           'mute': False,
                           'nick': None,
                           'pending': False,
                           'permissions': '1099511627775',
                           'premium_since': None,
                           'roles': [],
                           'user': {'avatar': 'b437e9bd4b0e487a097c4538c6cdce3f',
                                    'discriminator': '2585',
                                    'id': '185846097284038656',
                                    'public_flags': 0,
                                    'username': 'Soton'}},
                'token': 'aW50ZXJhY3Rpb246ODkyNTM0MDUwNzE4MzUxMzYwOks3MHEyT1ZIa1VkTUNhRjU3SmphcWY5d0k3SHc2TktoN3hweEQ5aUN6T2lkUXdKNDRmTGVQaWxEUEZ5UGpuVVV6ZjlVTlNQQ0FQVkROeXV6Sm1WMFFKQ1dXcEl1bFdScHIwS'
                'Vp4Ukw2cjQySVRJU3haclFJbHBMUGlBcm12ZTlC',
                'type': 2,
                'version': 1}

message_trigger_interaction = {'application_id': '889065662641737791',
                               'channel_id': '804392362629267458',
                               'data': {'id': '892668575582679050',
                                        'name': 'message',
                                        'resolved': {'messages': {'892668572126576661': {'attachments': [],
                                                                                         'author': {'avatar': 'b437e9bd4b0e487a097c4538c6cdce3f',
                                                                                                    'discriminator': '2585',
                                                                                                    'id': '185846097284038656',
                                                                                                    'public_flags': 0,
                                                                                                    'username': 'Soton'},
                                                                                         'channel_id': '804392362629267458',
                                                                                         'components': [],
                                                                                         'content': '<@!889065662641737791> '
                                                                                         'REGISTER',
                                                                                         'edited_timestamp': None,
                                                                                         'embeds': [],
                                                                                         'flags': 0,
                                                                                         'id': '892668572126576661',
                                                                                         'mention_everyone': False,
                                                                                         'mention_roles': [],
                                                                                         'mentions': [{'avatar': None,
                                                                                                       'bot': True,
                                                                                                       'discriminator': '8248',
                                                                                                       'id': '889065662641737791',
                                                                                                       'public_flags': 0,
                                                                                                       'username': 'test-bot'}],
                                                                                         'pinned': False,
                                                                                         'timestamp': '2021-09-29T07:06:12.575000+00:00',
                                                                                         'tts': False,
                                                                                         'type': 0}}},
                                        'target_id': '892668572126576661',
                                        'type': 3},
                               'guild_id': '804392362054910047',
                               'id': '892668771691528212',
                               'member': {'avatar': None,
                                          'deaf': False,
                                          'is_pending': False,
                                          'joined_at': '2021-01-28T16:48:04.105000+00:00',
                                          'mute': False,
                                          'nick': None,
                                          'pending': False,
                                          'permissions': '1099511627775',
                                          'premium_since': None,
                                          'roles': [],
                                          'user': {'avatar': 'b437e9bd4b0e487a097c4538c6cdce3f',
                                                   'discriminator': '2585',
                                                   'id': '185846097284038656',
                                                   'public_flags': 0,
                                                   'username': 'Soton'}},
                               'token': 'aW50ZXJhY3Rpb246ODkyNjY4NzcxNjkxNTI4MjEyOk5sdEh6VE9iWmVSeDc1bFBrN3cxalFqTHJBS3dpc3ZkdUxQMWs3aVhwbldvWjVtZHl2YWJOaVoxdFVoMWRIWlRTMUpVQkpvT3lwcVJ4UzJhZldHUlRMMl'
                               'hUU085NGVVYUtZVWtrd050R21FMHpvTTV2Vnpnd1J2V2tYeURTTXI5',
                               'type': 2,
                               'version': 1}

nested_groups = {'application_id': '889065662641737791',
                 'channel_id': '804392362629267458',
                 'data': {'id': '896591400626434069',
                          'name': 'complex',
                          'options': [{'name': 'edit',
                                       'options': [{'name': 'user',
                                                    'options': [{'name': 'target',
                                                                 'type': 6,
                                                                 'value': '185846097284038656'}],
                                                    'type': 1}],
                                       'type': 2}],
                          'resolved': {'members': {'185846097284038656': {'avatar': None,
                                                                          'is_pending': False,
                                                                          'joined_at': '2021-01-28T16:48:04.105000+00:00',
                                                                          'nick': None,
                                                                          'pending': False,
                                                                          'permissions': '1099511627775',
                                                                          'premium_since': None,
                                                                          'roles': []}},
                                       'users': {'185846097284038656': {'avatar': 'b437e9bd4b0e487a097c4538c6cdce3f',
                                                                        'discriminator': '2585',
                                                                        'id': '185846097284038656',
                                                                        'public_flags': 0,
                                                                        'username': 'Soton'}}},
                          'type': 1},
                 'guild_id': '804392362054910047',
                 'id': '896591465755578408',
                 'member': {'avatar': None,
                            'deaf': False,
                            'is_pending': False,
                            'joined_at': '2021-01-28T16:48:04.105000+00:00',
                            'mute': False,
                            'nick': None,
                            'pending': False,
                            'permissions': '1099511627775',
                            'premium_since': None,
                            'roles': [],
                            'user': {'avatar': 'b437e9bd4b0e487a097c4538c6cdce3f',
                                     'discriminator': '2585',
                                     'id': '185846097284038656',
                                     'public_flags': 0,
                                     'username': 'Soton'}},
                 'token': 'aW50ZXJhY3Rpb246ODk2NTkxNDY1NzU1NTc4NDA4OjkxM0pTeXJXZGQ2YmFWb0NpSXJwU0V3blRJMkFtcXVnZGFHYWRTWk9FZ1Fka3l1eDJEUmFLVE5GT2o1T3hsU1I3cEltbmtPSXJHTmtxOHhDRHJoVTl6Z3QzTEduNFRhS3N6'
                 'dVdUUlZXT0o5aTJOM00ycHlkYTdwWGE1dEo3eUcz',
                 'type': 2,
                 'version': 1}

all_types = {'application_id': '889065662641737791',
             'channel_id': '804392362629267458',
             'data': {'id': '898060972198068265',
                      'name': 'complex',
                      'options': [{'name': 'channel',
                                   'type': 7,
                                   'value': '889282264507248650'},
                                  {'name': 'user',
                                   'type': 6,
                                   'value': '185846097284038656'},
                                  {'name': 'int', 'type': 4, 'value': 13},
                                  {'name': 'mention',
                                   'type': 9,
                                   'value': '804392362054910047'},
                                  {'name': 'float', 'type': 10, 'value': 123.4},
                                  {'name': 'string', 'type': 3, 'value': 'asdf'},
                                  {'name': 'bool', 'type': 5, 'value': False},
                                  {'name': 'role',
                                   'type': 8,
                                   'value': '891182614428418088'},
                                  {'name': 'mentionable',
                                   'type': 9,
                                   'value': '889065662641737791'}],
                      'resolved': {'channels': {'889282264507248650': {'id': '889282264507248650',
                                                                       'name': 'general2',
                                                                       'parent_id': '804392362629267456',
                                                                       'permissions': '1099511627775',
                                                                       'type': 0}},
                                   'members': {'185846097284038656': {'avatar': None,
                                                                      'is_pending': False,
                                                                      'joined_at': '2021-01-28T16:48:04.105000+00:00',
                                                                      'nick': None,
                                                                      'pending': False,
                                                                      'permissions': '1099511627775',
                                                                      'premium_since': None,
                                                                      'roles': []},
                                               '889065662641737791': {'avatar': None,
                                                                      'is_pending': False,
                                                                      'joined_at': '2021-09-25T04:41:32.678000+00:00',
                                                                      'nick': None,
                                                                      'pending': False,
                                                                      'permissions': '1099511627775',
                                                                      'premium_since': None,
                                                                      'roles': ['891182614428418088']}},
                                   'roles': {'804392362054910047': {'color': 0,
                                                                    'hoist': False,
                                                                    'icon': None,
                                                                    'id': '804392362054910047',
                                                                    'managed': False,
                                                                    'mentionable': False,
                                                                    'name': '@everyone',
                                                                    'permissions': '1071698660929',
                                                                    'position': 0,
                                                                    'unicode_emoji': None},
                                             '891182614428418088': {'color': 0,
                                                                    'hoist': False,
                                                                    'icon': None,
                                                                    'id': '891182614428418088',
                                                                    'managed': True,
                                                                    'mentionable': False,
                                                                    'name': 'test-bot',
                                                                    'permissions': '8',
                                                                    'position': 1,
                                                                    'tags': {'bot_id': '889065662641737791'},
                                                                    'unicode_emoji': None}},
                                   'users': {'185846097284038656': {'avatar': 'b437e9bd4b0e487a097c4538c6cdce3f',
                                                                    'discriminator': '2585',
                                                                    'id': '185846097284038656',
                                                                    'public_flags': 0,
                                                                    'username': 'Soton'},
                                             '889065662641737791': {'avatar': None,
                                                                    'bot': True,
                                                                    'discriminator': '8248',
                                                                    'id': '889065662641737791',
                                                                    'public_flags': 0,
                                                                    'username': 'test-bot'}}},
                      'type': 1},
             'guild_id': '804392362054910047',
             'id': '901294224211853332',
             'member': {'avatar': None,
                        'deaf': False,
                        'is_pending': False,
                        'joined_at': '2021-01-28T16:48:04.105000+00:00',
                        'mute': False,
                        'nick': None,
                        'pending': False,
                        'permissions': '1099511627775',
                        'premium_since': None,
                        'roles': [],
                        'user': {'avatar': 'b437e9bd4b0e487a097c4538c6cdce3f',
                                 'discriminator': '2585',
                                 'id': '185846097284038656',
                                 'public_flags': 0,
                                 'username': 'Soton'}},
             'token': 'aW50ZXJhY3Rpb246OTAxMjk0MjI0MjExODUzMzMyOjNPc0hWN1gzRUh5REZIUEdHV3JDNDJTa01JN21SVHk3RGdGajR4Y2J0VkRUSlFGR05mRnNJcldjak5sYko2S0dkUEwxVUpleGRuUWxUUmJuWWFCVlg4VDVvTkNhelNnc3dmWW5O'
             'OXFNNHdwVnlWb0JSR2lNUENyTmhoSkVTZTlC',
             'type': 2,
             'version': 1}


target = pathlib.Path(pathlib.Path(__file__).parent, 'raw_INTERACTION_CREATE_samples.json')
with open(target) as fp:
    raw_interaction_create_samples = json.load(fp)
