example_connect = {
    'application': {'flags': 303104, 'id': '889065662641737791'},
    'geo_ordered_rtc_regions': ['us-south',
                                'us-central',
                                'santa-clara',
                                'us-west',
                                'seattle'],
    'guild_join_requests': [],
    'guilds': [{'id': '804392362054910047', 'unavailable': True}],
    'presences': [],
    'private_channels': [],
    'relationships': [],
    'session_id': 'd32c822f49f8009ff00f4caa663eebb3',
    'user': {'avatar': None,
             'bot': True,
             'discriminator': '8248',
             'email': None,
             'flags': 0,
             'id': '889065662641737791',
             'mfa_enabled': True,
             'username': 'test-bot',
             'verified': True},
    'user_settings': {},
    'v': 9}
