name: Codecov
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Coverage:
    runs-on: self-hosted
    name: "Code Coverage"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: python3 -m pip install --upgrade  pip
      - run: python3 -m pip install -r tests/requirements_test.txt
      - run: python3 -m pip install -r requirements.txt
      - name: "Test: pytest"
        run: python3 -m pytest --cov=src --durations=5 -vv --color=yes tests
      - name: "Produce coverage XML"
        run: coverage xml
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
